version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: telegram-bot-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: telegram_db
    ports:
      - "5433:5432"
    volumes:
      - telegram_bot_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: telegram-bot-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      MONGO_INITDB_DATABASE: telegram_db
    ports:
      - "27017:27017"
    volumes:
      - telegram_mongo_data:/data/db

volumes:
  telegram_bot_data:
  telegram_mongo_data: